export function drawNorthIndianChartToCanvas(canvas, data) {
  const ctx = canvas.getContext("2d");
  const W = canvas.width,
    H = canvas.height;

  // background
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, W, H);

  // title
  ctx.fillStyle = "#111827";
  ctx.font = "bold 28px system-ui, -apple-system, Segoe UI";
  ctx.fillText(data.title || "Kundali", 28, 48);

  // chart area
  const cx = W / 2,
    cy = H / 2;
  const size = Math.min(W, H) * 0.7;
  const r = size / 2;
  const points = [
    [cx, cy - r], // top
    [cx + r, cy], // right
    [cx, cy + r], // bottom
    [cx - r, cy], // left
  ];

  // diamond outline
  ctx.strokeStyle = "#111827";
  ctx.lineWidth = 3;
  ctx.beginPath();
  ctx.moveTo(points[0][0], points[0][1]);
  for (let i = 1; i < points.length; i++)
    ctx.lineTo(points[i][0], points[i][1]);
  ctx.closePath();
  ctx.stroke();

  // inner lines (simple grid)
  ctx.lineWidth = 1.5;
  const mid = (a, b) => [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2];
  const m01 = mid(points[0], points[1]);
  const m12 = mid(points[1], points[2]);
  const m23 = mid(points[2], points[3]);
  const m30 = mid(points[3], points[0]);
  const center = [cx, cy];

  // draw diagonals
  ctx.beginPath();
  ctx.moveTo(points[0][0], points[0][1]);
  ctx.lineTo(points[2][0], points[2][1]);
  ctx.moveTo(points[1][0], points[1][1]);
  ctx.lineTo(points[3][0], points[3][1]);
  ctx.stroke();

  // draw box splits
  ctx.beginPath();
  ctx.moveTo(m01[0], m01[1]);
  ctx.lineTo(m23[0], m23[1]);
  ctx.moveTo(m12[0], m12[1]);
  ctx.lineTo(m30[0], m30[1]);
  ctx.stroke();

  // Write key data
  ctx.fillStyle = "#374151";
  ctx.font = "16px system-ui, -apple-system";
  ctx.fillText(`Rashi: ${data.rashi || "-"}`, 28, H - 84);
  ctx.fillText(
    `Nakshatra: ${data.nakshatra || "-"} (Pada ${data.nakshatraPada || "-"})`,
    28,
    H - 56
  );

  // planets list (moon highlighted)
  const planets = data.planets || {};
  const labels = Object.keys(planets);
  ctx.font = "14px system-ui, -apple-system";
  labels.forEach((k, i) => {
    const y = 100 + i * 22;
    const deg = planets[k];
    if (k === "moon") ctx.fillStyle = "#4f46e5";
    else ctx.fillStyle = "#111827";
    ctx.fillText(
      `${k.toUpperCase()}: ${
        typeof deg === "number" ? deg.toFixed(2) + "°" : "-"
      }`,
      W - 300,
      y
    );
  });

  // signature
  ctx.fillStyle = "#9CA3AF";
  ctx.font = "12px system-ui, -apple-system";
  ctx.fillText("Generated by Kundali Matcher", 28, H - 24);
}
